local G = require("game_mock")
local P = require("panel_mock")
local minimap = require("minimap")

local function host(saved)
  local h = { opens = 0, toggles = 0, saved = saved }
  h.open = function() h.opens = h.opens + 1 end
  h.toggle = function() h.toggles = h.toggles + 1 end
  h.angle = function() return h.saved end
  h.save = function(a) h.saved = a end
  return h
end

describe("minimap button", function()
  before_each(function()
    G.install({})
    P.install()
  end)

  it("sits on the rim: a circle, or the edge of a square minimap", function()
    local x, y = minimap.offset(0, "ROUND")
    assert.are.near(80, x, 1e-9)
    assert.are.near(0, y, 1e-9)
    x, y = minimap.offset(90, nil)
    assert.are.near(0, x, 1e-9)
    assert.are.near(80, y, 1e-9)
    x, y = minimap.offset(45, "ROUND")
    assert.are.near(80 / math.sqrt(2), x, 1e-9)
    x, y = minimap.offset(45, "SQUARE")
    assert.are.near(80, x, 1e-9)
    assert.are.near(80, y, 1e-9)
    x, y = minimap.offset(180, "SQUARE", 50)
    assert.are.near(-50, x, 1e-9)
    assert.are.near(0, y, 1e-9)
    assert.are.near(135, minimap.angle(0, 0, -1, 1), 1e-9)
    assert.are.near(270, minimap.angle(10, 10, 10, 0), 1e-9)
    assert.are.near(0, minimap.angle(10, 10, 20, 10), 1e-9)
  end)

  -- ElvUI's square minimap is 176 px and resizable: the rim is half its width out, plus a little
  it("the rim follows the minimap's size", function()
    Minimap:SetWidth(220)
    assert.are.near(115, minimap.radius(), 1e-9)
    Minimap:SetWidth(0)
    assert.are.equal(minimap.RADIUS, minimap.radius())
  end)

  it("is a child of the minimap at its saved angle, or the default one", function()
    local b = minimap.new(host())
    assert.are.equal(b, DoubtMyRotationMinimapButton)
    assert.are.equal(minimap.NAME, b.name)
    assert.are.equal("minimap", b.kind)
    assert.truthy(b.icon)
    assert.truthy(b.border)
    local x, y = minimap.offset(minimap.ANGLE, "ROUND")
    assert.are.same({ "CENTER", Minimap, "CENTER", x, y }, b.point)
    assert.is_true(Minimap.kids[1] == b)
    local again = minimap.new(host(90))
    assert.are.near(80, again.point[5], 1e-9)
    again:place(0)
    assert.are.near(80, again.point[4], 1e-9)
    assert.are.equal(1, #again.points)
  end)

  it("never touches the minimap's own scripts", function()
    local b = minimap.new(host())
    b.scripts.OnDragStart(b)
    b.scripts.OnUpdate(b, 0.016)
    b.scripts.OnDragStop(b)
    assert.are.same({}, Minimap.scripts)
    assert.are.same({}, Minimap.hooks)
  end)

  it("left click opens the settings, right click shows or hides the timeline", function()
    local h = host()
    local b = minimap.new(h)
    b.scripts.OnClick(b, "LeftButton")
    b.scripts.OnClick(b, "RightButton")
    assert.are.same({ 1, 1 }, { h.opens, h.toggles })
    assert.are.same({ "LeftButtonUp", "RightButtonUp" }, b.clicks)
    assert.are.same({ "LeftButton" }, b.drag)
  end)

  it("dragged, it follows the cursor round the rim and saves where it stopped", function()
    local h = host()
    G.cfg.cursor = { 1000, 800 } -- straight above the minimap's center (1000, 700)
    local b = minimap.new(h)
    assert.is_nil(b.scripts.OnUpdate)
    b.scripts.OnDragStart(b)
    assert.is_function(b.scripts.OnUpdate)
    b.scripts.OnUpdate(b, 0.016)
    assert.are.near(0, b.point[4], 1e-9)
    assert.are.near(80, b.point[5], 1e-9)
    b.scripts.OnDragStop(b)
    assert.is_nil(b.scripts.OnUpdate)
    assert.are.near(90, h.saved, 1e-9)
  end)

  it("reads the cursor in the minimap's scale", function()
    local h = host()
    Minimap.scale = 2 -- the minimap's center (1000, 700) is at (2000, 1400) screen pixels
    G.cfg.cursor = { 1900, 1400 }
    local b = minimap.new(h)
    b.scripts.OnDragStart(b)
    b.scripts.OnUpdate(b, 0.016)
    b.scripts.OnDragStop(b)
    assert.are.near(180, h.saved, 1e-9)
  end)

  it("a square minimap (ElvUI) puts it on the square's edge", function()
    G.install({ minimapShape = "SQUARE" })
    P.install()
    local b = minimap.new(host(45))
    assert.are.near(80, b.point[4], 1e-9)
    assert.are.near(80, b.point[5], 1e-9)
  end)

  it("says what its clicks do on hover", function()
    local b = minimap.new(host())
    b.scripts.OnEnter(b)
    assert.are.equal(minimap.TIP, G.tooltip.text)
    assert.are.equal(b, G.tooltip.owner)
    assert.truthy(G.tooltip.text:find("Right-click", 1, true))
    b.scripts.OnLeave(b)
    assert.is_false(G.tooltip.shown)
  end)
end)
