local enemies = require("enemies")

local ME = "0x01"

describe("enemies", function()
  it("starts empty", function()
    local e = enemies.new()
    local m, n = e:counts(100)
    assert.are.equal(0, m)
    assert.are.equal(0, n)
  end)

  it("counts distinct melee attackers of the player", function()
    local e = enemies.new()
    e:onEvent(100.0, "SWING_DAMAGE", "0xA", ME, ME)
    e:onEvent(100.5, "SWING_MISSED", "0xB", ME, ME)
    e:onEvent(101.0, "SWING_DAMAGE", "0xA", ME, ME)
    local m, n = e:counts(101.0)
    assert.are.equal(2, m)
    assert.are.equal(2, n)
  end)

  it("melee attackers expire after 2.5 s but stay nearby until 6 s", function()
    local e = enemies.new()
    e:onEvent(100.0, "SWING_DAMAGE", "0xA", ME, ME)
    local m, n = e:counts(102.6)
    assert.are.equal(0, m)
    assert.are.equal(1, n)
    m, n = e:counts(106.1)
    assert.are.equal(0, n)
  end)

  it("spell damage to the player counts as nearby, not melee", function()
    local e = enemies.new()
    e:onEvent(100, "SPELL_DAMAGE", "0xC", ME, ME)
    local m, n = e:counts(100)
    assert.are.equal(0, m)
    assert.are.equal(1, n)
  end)

  it("player's outgoing damage marks targets as nearby", function()
    local e = enemies.new()
    e:onEvent(100, "SPELL_DAMAGE", ME, "0xA", ME)
    e:onEvent(100, "SWING_DAMAGE", ME, "0xB", ME)
    e:onEvent(100, "SPELL_PERIODIC_DAMAGE", ME, "0xC", ME)
    local _, n = e:counts(100)
    assert.are.equal(3, n)
  end)

  it("damage done by a summoned totem counts as the player's", function()
    local e = enemies.new()
    e:onEvent(100, "SPELL_SUMMON", ME, "0xT", ME)
    e:onEvent(101, "SPELL_DAMAGE", "0xT", "0xA", ME)
    e:onEvent(101, "SPELL_DAMAGE", "0xT", "0xB", ME)
    local _, n = e:counts(101)
    assert.are.equal(2, n)
  end)

  it("ignores events not involving the player or own summons", function()
    local e = enemies.new()
    e:onEvent(100, "SPELL_DAMAGE", "0xX", "0xY", ME)
    e:onEvent(100, "SPELL_HEAL", ME, "0xA", ME)
    e:onEvent(100, "SPELL_AURA_APPLIED", "0xA", ME, ME)
    local m, n = e:counts(100)
    assert.are.equal(0, m)
    assert.are.equal(0, n)
  end)

  it("removes dead units immediately", function()
    local e = enemies.new()
    e:onEvent(100, "SWING_DAMAGE", "0xA", ME, ME)
    e:onEvent(100, "SWING_DAMAGE", "0xB", ME, ME)
    e:onEvent(100.5, "UNIT_DIED", nil, "0xA", ME)
    local m, n = e:counts(100.5)
    assert.are.equal(1, m)
    assert.are.equal(1, n)
  end)

  it("PARTY_KILL removes the killed unit", function()
    local e = enemies.new()
    e:onEvent(100, "SPELL_DAMAGE", ME, "0xA", ME)
    e:onEvent(100.2, "PARTY_KILL", ME, "0xA", ME)
    local _, n = e:counts(100.2)
    assert.are.equal(0, n)
  end)

  it("nearby is never below melee", function()
    local e = enemies.new()
    e:onEvent(100, "SWING_DAMAGE", "0xA", ME, ME)
    local m, n = e:counts(100)
    assert.is_true(n >= m)
  end)

  it("ignores nil subEvent safely", function()
    local e = enemies.new()
    e:onEvent(100, nil, nil, nil, ME)
    local m = e:counts(100)
    assert.are.equal(0, m)
  end)
end)
