local W = require("wow_mock")
local F = require("fixtures")

describe("test harness", function()
  it("mock returns shaman spell info with 3.3.5 layout", function()
    W.install({ known = { [49238] = true }, castMs = { [49238] = 2500 } })
    local name, rank, icon, cost, _, _, castMs = GetSpellInfo(49238)
    assert.are.equal("Lightning Bolt", name)
    assert.are.equal("Rank 14", rank)
    assert.are.equal(2500, castMs)
    assert.is_true(IsSpellKnown(49238))
    assert.is_false(IsSpellKnown(403))
  end)

  it("mock tooltip exposes weapon enchant text", function()
    W.install({ enchants = { mh = "Windfury", oh = "Flametongue" }, weapons = { mh = { 1, 2, 2.6 }, oh = { 1, 2, 2.6 } } })
    W.frames()
    local tip = CreateFrame("GameTooltip", "EnhRotScan")
    tip:SetInventoryItem("player", 17)
    assert.are.equal("Flametongue (30 min)", _G["EnhRotScanTextLeft2"]:GetText())
  end)

  it("fixture state has every contract field and merges patches deeply", function()
    local S = F.state({ buffs = { mw = { stacks = 5 } }, target = { fs = 0 } })
    assert.are.equal(5, S.buffs.mw.stacks)
    assert.are.equal(0, S.buffs.mw.remains)
    assert.are.equal(0, S.target.fs)
    assert.are.equal(83, S.target.level)
    for _, k in ipairs({ "now", "gcdRemains", "castRemains", "gcd", "latency", "mode", "player", "weapons",
                         "talents", "spells", "buffs", "target", "totems", "swing", "enemies", "inflight" }) do
      assert.is_not_nil(S[k], k)
    end
  end)

  it("F.only keeps just the given spells", function()
    local S = F.only(F.state(), "earthShock", "lightningBolt")
    assert.is_not_nil(S.spells.earthShock)
    assert.is_nil(S.spells.stormstrike)
  end)
  it("fixture defaults follow contract v2", function()
    local S = F.state()
    assert.are.equal("group", S.mode)
    assert.is_true(S.swing.attacking)
    assert.are.same({ 1e6, 1e6, 60 }, { S.target.hp, S.target.hpMax, S.target.ttd })
    assert.are.same({ wolves = 0 }, S.pets)
    assert.is_nil(S.weapons.mh.twoHand)
    assert.is_nil(S.target.dead)
    assert.is_nil(S.target.armor)
    local n = 0
    for _, sp in pairs(S.spells) do n = n + 1; assert.are.equal(0, sp.cd) end
    assert.are.equal(15, n)
    assert.are.equal(false, F.state({ totems = { fire = { kind = false } } }).totems.fire.kind)
    S.spells.stormstrike.cd = 5
    assert.are.equal(0, F.SPELLS80.stormstrike.cd)
  end)

  it("damage stub returns fixed numbers and AoE target counts", function()
    local d = require("stubs").damage({ lightningBolt = 1 })
    local S = F.state({ enemies = { nearby = 5 } })
    assert.are.equal(1, d.action(S, "lightningBolt"))
    assert.are.equal(2000, d.action(S, "stormstrike"))
    assert.are.same({ 300, 4, 3 }, { d.dot(S, "flameShock") })
    assert.are.same({ 0, 0, 1 }, { d.dot(S, "earthShock") })
    assert.are.equal(5, d.targets(S, "fireNova"))
    assert.are.equal(3, d.targets(S, "chainLightning"))
    assert.are.equal(1, d.targets(S, "stormstrike"))
  end)
end)
