#!/usr/bin/env python3
"""Generate src/spells_data.lua from the 3.3.5a client Spell.dbc.

Usage: python3 tools/spelldata.py data/Spell.dbc src/spells_data.lua
"""
import struct
import sys

F_ID, F_CAST_IDX, F_RECOVERY, F_CAT_RECOVERY, F_LEVEL = 0, 28, 29, 30, 39
F_EFFECT, F_DIE, F_BASE, F_AURA, F_AMPL = 71, 74, 80, 95, 98
F_GCD, F_BONUS = 206, 229
EFFECT_SCHOOL_DAMAGE, EFFECT_APPLY_AURA, EFFECT_WEAPON_PERCENT = 2, 6, 31
AURA_PERIODIC_DAMAGE = 3

# SpellCastTimes.dbc index -> base cast time in ms (only indexes used by these spells)
CAST_MS = {1: 0, 5: 2000, 16: 1500, 19: 2500}

# DoT durations in seconds. SpellDuration.dbc is not extracted; Flame Shock uses DurationIndex 85,
# which is 18 s (the same index 29 = 12 s that Stormstrike uses would give 4 ticks; 139 x 6 = 834 matches the tooltip).
DOT_DURATION = {"flameShock": 18.0}

# weapon strikes whose percent is not in an effect of the learn spell
WEAPON_PCT = {"stormstrike": 100}


def pairs(learn, dmg=None):
    """Zip learn-spell ids with damage-spell ids (same id when dmg is None)."""
    return list(zip(learn, dmg if dmg else learn))


RANKS = {
    "lightningBolt": pairs([403, 529, 548, 915, 943, 6041, 10391, 10392, 15207, 15208, 25448, 25449, 49237, 49238]),
    "chainLightning": pairs([421, 930, 2860, 10605, 25439, 25442, 49270, 49271]),
    "earthShock": pairs([8042, 8044, 8045, 8046, 10412, 10413, 10414, 25454, 49230, 49231]),
    "flameShock": pairs([8050, 8052, 8053, 10447, 10448, 29228, 25457, 49232, 49233]),
    "frostShock": pairs([8056, 8058, 10472, 10473, 25464, 49235, 49236]),
    "stormstrike": pairs([17364]),
    "lavaLash": pairs([60103]),
    "searingTotem": pairs([3599, 6363, 6364, 6365, 10437, 10438, 25533, 58699, 58703, 58704],
                          [3606, 6350, 6351, 6352, 10435, 10436, 25530, 58700, 58701, 58702]),
    "magmaTotem": pairs([8190, 10585, 10586, 10587, 25552, 58731, 58734],
                        [8187, 10579, 10580, 10581, 25550, 58732, 58735]),
    "fireNova": pairs([1535, 8498, 8499, 11314, 11315, 25546, 25547, 61649, 61657],
                      [8349, 8502, 8503, 11306, 11307, 25535, 25537, 61650, 61654]),
    "fireElemental": pairs([2894]),
    "callOfElements": pairs([66842]),
    "lightningShield": pairs([324, 325, 905, 945, 8134, 10431, 10432, 25469, 25472, 49280, 49281],
                             [26364, 26365, 26366, 26367, 26369, 26370, 26363, 26371, 26372, 49278, 49279]),
    "shamanisticRage": pairs([30823]),
    "feralSpirit": pairs([51533]),
}


def load(path):
    data = open(path, "rb").read()
    magic, count, fields, size, _ = struct.unpack("<4s4I", data[:20])
    if magic != b"WDBC" or fields != 234:
        raise SystemExit("unexpected Spell.dbc layout: %r %d" % (magic, fields))
    rows = {}
    for i in range(count):
        row = struct.unpack("<%dI" % fields, data[20 + i * size:20 + (i + 1) * size])
        rows[row[F_ID]] = row
    return rows


def f32(u):
    return round(struct.unpack("<f", struct.pack("<I", u))[0], 4)


def signed(u):
    return u - 2 ** 32 if u >= 2 ** 31 else u


def effect(row, kind, aura=None):
    for k in range(3):
        if row[F_EFFECT + k] == kind and (aura is None or row[F_AURA + k] == aura):
            base = signed(row[F_BASE + k])
            return {"min": base + 1, "max": base + max(row[F_DIE + k], 1),
                    "coef": f32(row[F_BONUS + k]), "ampl": row[F_AMPL + k]}
    return None


def entry(key, learn, dmg):
    cast_idx = learn[F_CAST_IDX]
    if cast_idx not in CAST_MS:
        raise SystemExit("unknown cast index %d for %s %d" % (cast_idx, key, learn[F_ID]))
    e = {"id": learn[F_ID], "dmgId": dmg[F_ID], "level": learn[F_LEVEL], "castMs": CAST_MS[cast_idx], "gcdMs": learn[F_GCD],
         "cdMs": max(learn[F_RECOVERY], learn[F_CAT_RECOVERY]),
         "min": 0, "max": 0, "coef": 0, "weaponPct": WEAPON_PCT.get(key, 0)}
    direct = effect(dmg, EFFECT_SCHOOL_DAMAGE)
    if direct:
        e.update(min=direct["min"], max=direct["max"], coef=direct["coef"])
    weapon = effect(learn, EFFECT_WEAPON_PERCENT)
    if weapon:
        e["weaponPct"] = weapon["min"]
    dot = effect(dmg, EFFECT_APPLY_AURA, AURA_PERIODIC_DAMAGE)
    if dot and key in DOT_DURATION:
        e.update(tick=dot["min"], tickCoef=dot["coef"], ticks=int(round(DOT_DURATION[key] * 1000 / dot["ampl"])),
                 period=dot["ampl"] / 1000.0)
    return e


FIELD_ORDER = ["id", "dmgId", "level", "castMs", "gcdMs", "cdMs", "min", "max", "coef", "weaponPct", "tick", "tickCoef", "ticks", "period"]


def lua_num(v):
    return repr(v) if isinstance(v, float) else str(v)


def render(table):
    out = ["-- GENERATED by tools/spelldata.py from the client Spell.dbc. Do not edit by hand.", "return {"]
    for key in sorted(table):
        out.append("  %s = {" % key)
        for e in table[key]:
            parts = ["%s = %s" % (f, lua_num(e[f])) for f in FIELD_ORDER if f in e]
            out.append("    { %s }," % ", ".join(parts))
        out.append("  },")
    out.append("}")
    return "\n".join(out) + "\n"


def main(src, dst):
    rows = load(src)
    table = {}
    for key, ids in RANKS.items():
        entries = []
        for learn_id, dmg_id in ids:
            if learn_id not in rows or dmg_id not in rows:
                raise SystemExit("spell %d/%d for %s not found in DBC" % (learn_id, dmg_id, key))
            entries.append(entry(key, rows[learn_id], rows[dmg_id]))
        table[key] = sorted(entries, key=lambda e: (e["level"], e["id"]))
    open(dst, "w").write(render(table))
    print("%s: %d spells, %d ranks" % (dst, len(table), sum(len(v) for v in table.values())))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
